Fix build on Darwin
rust-motd/rust-motd pull request #21
Opened 2022-04-03 10:01 UTC by NickLarsenNZ

Fixes #20 

- Conditionally ignore memory stats on non linux/android platforms. Darwin is not supported by systemstat (https://github.com/unrelentingtech/systemstat/issues/73).
- Fixed a error output string for MemoryError

2022-04-03 16:03 UTC, MarcelRobitaille requested changes
I have no way to test this, but it seems like a reasonable workaround.

2022-04-03 16:03 UTC, MarcelRobitaille commented on src/components/memory.rs
> +    #[error("Getting memory information is not supported on the current platform")]
Should we link to the relevant issue (https://github.com/rust-motd/rust-motd/issues/20) here?

2022-04-03 16:03 UTC, MarcelRobitaille commented on src/main.rs
> +                    .unwrap_or_else(|err| println!("Memory error: {}", err));
Nice catch :)

2022-04-03 16:25 UTC, NickLarsenNZ commented on src/components/memory.rs
> +    #[error("Getting memory information is not supported on the current platform")]
As a code comment, or in the error text?

2022-04-03 16:27 UTC, NickLarsenNZ commented
I ran it on my Mac, the warnings are still there but if you like I can allow `dead_code` and `unused_variables`?

2022-04-03 16:28 UTC, NickLarsenNZ commented
Oh, also I'm working on Mac support for systemstat so hopefully will have something soon.

2022-04-03 17:10 UTC, MarcelRobitaille commented on src/components/memory.rs
> +    #[error("Getting memory information is not supported on the current platform")]
I was thinking in the error message so that users can see why it's unsupported.

2022-04-03 17:11 UTC, MarcelRobitaille commented
> Oh, also I'm working on Mac support for systemstat so hopefully will have something soon.

I hope so as well. We could also consider switching to heim as recommended in that issue.

2022-04-03 21:47 UTC, NickLarsenNZ commented on src/components/memory.rs
> +    #[error("Getting memory information is not supported on the current platform")]
Oh right. I'm not sure it's all that helpful for an end user and just ends up being noise. It is useful for a developer, thought they can find it through references in the commit messages.

I can add it if it's a show stopper though.

2022-04-04 02:49 UTC, MarcelRobitaille commented on src/components/memory.rs
> +    #[error("Getting memory information is not supported on the current platform")]
I think it's important to let people know why something is not working. I guess in this case it isn't very helpful if the solution is that it's not supported on their computer. I just really hate those error messages that are super vague and difficult to debug, so maybe I'm projecting from that.

I think the users of this program are very technical. Maybe it will matter so much to someone that they follow this discussion and make a PR switching to heim.

I guess it's not a show stopper for me. I would also be fine with a short "(see issue #20)" (no link).

2022-04-04 05:20 UTC, NickLarsenNZ commented on src/components/memory.rs
> +    #[error("Getting memory information is not supported on the current platform")]
Sounds fair. I've pushed the change now.

2022-04-04 05:22 UTC, merged