filesystems: Use IndexMap instead of HashMap
rust-motd/rust-motd pull request #31
Opened 2024-12-20 10:41 UTC by wentasah

Before this change, the order of printed filesystems was different (random) in every invocation. With this change, the order is the same as in the configuration file.

2024-12-23 03:33 UTC, MarcelRobitaille commented
Hi @wentasah Thanks for your contribution. This looks great!

2024-12-23 03:45 UTC, MarcelRobitaille commented
The changes look good, but I wonder if this should be extended to all settings.

2024-12-23 10:04 UTC, wentasah commented
Yes, you're right that these components are also affected. I don't use them so I didn't notice. Anyway, I implemented similar change to them as well. Changes in most components were trivial, only the Docker component required some refactoring. So you may want to have a closer look there and test it with you setup. I'm not 100% sure, I kept the functionality unchanged.

2024-12-23 23:20 UTC, MarcelRobitaille requested changes
Looks good. I tested the docker stuff and it still seems to work.

2024-12-23 23:20 UTC, MarcelRobitaille commented on src/components/docker.rs
> +        let summary_hash: HashMap<String, ContainerSummary> = container_summaries
I would put a comment here to say why this is needed (since a container can have more than one name, make a hash indexed by name to look up based on the name in the config file). It took me a while to remember

2024-12-23 23:20 UTC, MarcelRobitaille commented on src/components/docker.rs
> +                    None => {
I like it :)

2024-12-24 00:41 UTC, wentasah commented on src/components/docker.rs
> +                    None => {
Comment added.

2024-12-24 00:42 UTC, wentasah commented
I also managed to create the hash with a reference to CommitSummary, so it is not unnecessarily cloned.

2024-12-24 03:47 UTC, MarcelRobitaille approved these changes

2024-12-24 03:47 UTC, merged